name: mergeDevIntoMain

on:
  workflow_dispatch:
  push:
    branches: ["development"]


env:
  # replace "github_username" with your GitHub username
  # replace "github.com/username/repo.git" with your GitHub repo path
  # do NOT replace ${{secrets.GITHUB_TOKEN}}, GitHub will take care of it
  # MY_REPO: https://github_username:${{secrets.GITHUB_TOKEN}}@github.com/username/repo.git
  MY_REPO: https://jeffreyally:${{secrets.GITHUB_TOKEN}}@github.com/jeffreyally/javaparser-maven-sample.git

  # replace "long-lived_branch_name" with your branch name
  MY_BRANCH: development

  # replace it with the path to master repo - https://github.com/username/master_repo.git 
  MASTER_REPO: https://github.com/jeffreyally/javaparser-maven-sample.git

  # replace "master" with your master branch name
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MASTER_BRANCH}} tmp
        cd tmp
        ls -l
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MY_BRANCH}}
        git branch -a
        temp=$(grep -P -o -m 1 "\d.\d.*-SNAPSHOT" ./pom.xml | head -1)
        find ./ -name "pom*" -exec sed -i "0,/"$temp"/{s/"$temp"/"${temp%-SNAPSHOT}"/}" {} \;
        git push
